server:
  transport: http
  port: 8089
  host: "0.0.0.0"

tools:
  - path: flux_mcp.job.flux_handle_delegation
  - path: flux_mcp.job.flux_submit_job
  - path: flux_mcp.job.flux_cancel_job
  - path: flux_mcp.job.flux_get_job_info
  - path: flux_mcp_server.tools.submit.flux_submit_batch

# prompts:
#  - path: hpc_mcp.t.build.docker.docker_build_persona_prompt
#    name: build_expert
